# Generated by Django 5.2.13 on 2026-05-18 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('task_type', models.CharField(choices=[('receive_goods', 'Принять товар'), ('place_goods', 'Разместить товар'), ('collect_order', 'Собрать заказ'), ('ship_goods', 'Отгрузить товар'), ('move_goods', 'Переместить товар'), ('inventory', 'Инвентаризация'), ('write_off', 'Списание')], max_length=50, verbose_name='Тип задачи')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена'), ('overdue', 'Просрочена')], default='created', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Складская задача',
                'verbose_name_plural': 'Складские задачи',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
    ]
