# Generated by Django 5.2.13 on 2026-05-18 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('product_created', 'Создание товара'), ('receipt_created', 'Поступление'), ('shipment_created', 'Отгрузка'), ('stock_moved', 'Перемещение'), ('write_off_created', 'Списание'), ('task_created', 'Создание задачи'), ('task_completed', 'Выполнение задачи'), ('report_exported', 'Экспорт отчета')], max_length=50, verbose_name='Тип операции')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Сущность')),
                ('entity_id', models.PositiveBigIntegerField(verbose_name='ID сущности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал операций',
                'verbose_name_plural': 'Журнал операций',
                'ordering': ['-created_at'],
            },
        ),
    ]
